export const CATEGORIES = [
  { id: "all", label: "Semua Produk" },
  { id: "sayur", label: "Sayuran Segar" },
  { id: "bumbu", label: "Bumbu & Rempah" },
  { id: "umbi", label: "Umbi & Akar" },
];

export const PRODUCTS = [
  { id:1, cat:"sayur",   name:"Tomat Merah Grade A",  price:12500, unit:"/kg", desc:"Dipanen pagi dari petani Cianjur. Matang sempurna, rendah pestisida.",        bulk:{min:50, pct:15}, visual:"prod-tomat",   tag:"STOK BANYAK" },
  { id:2, cat:"bumbu",   name:"Cabai Merah Keriting",  price:38000, unit:"/kg", desc:"Pedas konsisten, warna merata. Cocok untuk sambal dan tumisan.",             bulk:{min:20, pct:12}, visual:"prod-cabe",    tag:"PANEN HARI INI" },
  { id:3, cat:"sayur",   name:"Bayam Hijau Organik",   price:8500,  unit:"/ikat", desc:"Bebas pestisida kimia. Umur simpan 3–4 hari dalam cold chain.",           bulk:{min:30, pct:10}, visual:"prod-bayam",   tag:"ORGANIK" },
  { id:5, cat:"bumbu",   name:"Bawang Merah Brebes",   price:32000, unit:"/kg", desc:"Varietas Bima, sortir manual. Aroma tajam, cocok untuk bumbu dasar.",      bulk:{min:30, pct:14}, visual:"prod-bawang",  tag:"POPULER" },
  { id:6, cat:"umbi",    name:"Kentang Dieng",         price:14000, unit:"/kg", desc:"Daging kuning, tidak berair. Ideal untuk french fries dan perkedel.",     bulk:{min:50, pct:18}, visual:"prod-kentang", tag:"PEGUNUNGAN" },
  { id:7, cat:"bumbu",   name:"Jahe Merah",            price:42000, unit:"/kg", desc:"Serat halus, kadar oleoresin tinggi. Wajib untuk jamu dan minuman rempah.",bulk:{min:15, pct:10}, visual:"prod-jahe",    tag:"PREMIUM" },
  { id:8, cat:"umbi",    name:"Wortel Lokal Bandung",  price:11000, unit:"/kg", desc:"Manis alami, ukuran seragam. Cocok untuk sup, jus, dan salad.",           bulk:{min:40, pct:12}, visual:"prod-wortel",  tag:"STOK BANYAK" },
];

export const PRODUCT_GROUPS = [
  { id:"sayuran", label:"Sayuran", items:[
    { name:"Brokoli",          image:"/produk/BROKOLI.jpg",          desc:"Kuntum padat, warna hijau cerah. Cocok untuk tumis dan sup." },
    { name:"Buncis",           image:"/produk/BUNCIS.jpg",           desc:"Renyah dan segar. Ideal untuk tumisan dan campuran salad." },
    { name:"Caisim",           image:"/produk/CAISIM.jpg",           desc:"Daun lembut dengan batang renyah. Favorit untuk mi dan nasi goreng." },
    { name:"Daun Bayam",       image:"/produk/DAUN BAYAM.png",       desc:"Bebas pestisida, umur simpan panjang dalam cold chain." },
    { name:"Jagung",           image:"/produk/JAGUNG.jpg",           desc:"Manis alami, biji penuh. Cocok untuk sup, bakar, dan olahan." },
    { name:"Kacang Panjang",   image:"/produk/KACANG PANJANG.jpg",  desc:"Segar dan lentur. Pilihan tepat untuk tumis dan lalapan." },
    { name:"Kailan",           image:"/produk/KAILAN.jpg",           desc:"Tekstur renyah dengan rasa sedikit pahit khas. Ideal untuk tumis." },
    { name:"Kembang Kol",      image:"/produk/KEMBANG KOL.jpg",     desc:"Kuntum putih bersih, padat. Serbaguna untuk sup dan panggang." },
    { name:"Kentang",          image:"/produk/KENTANG.jpg",          desc:"Daging kuning, tidak berair. Ideal untuk goreng dan perkedel." },
    { name:"Kol",              image:"/produk/KOL.jpg",              desc:"Daun lebar dan renyah. Cocok untuk lalapan, tumis, dan acar." },
    { name:"Labu Siam",        image:"/produk/LABU SIAM.jpg",       desc:"Rasa netral, tekstur lembut. Pilihan ekonomis untuk sayur bening." },
    { name:"Lobak",            image:"/produk/LOBAK.jpg",            desc:"Rasa ringan dan segar. Cocok untuk sup dan kimchi." },
    { name:"Oyong",            image:"/produk/OYONG.jpg",            desc:"Ringan dan menyerap rasa. Cocok untuk sup bening dan tumisan." },
    { name:"Pak Choy",         image:"/produk/PAK CHOY.jpg",        desc:"Daun hijau segar dengan batang putih renyah. Serbaguna untuk masakan Asia." },
    { name:"Pare",             image:"/produk/PARE.jpg",             desc:"Pahit khas, kaya nutrisi. Cocok untuk tumis dan jus kesehatan." },
    { name:"Salada Keriting",  image:"/produk/SALADA KERITING.jpg", desc:"Daun renyah dan segar. Sempurna untuk salad dan garnish." },
    { name:"Sawi Hijau",       image:"/produk/SAWI HIJAU.jpg",      desc:"Rasa sedikit pahit yang khas. Pasangan wajib bakso dan mie." },
    { name:"Sawi Putih",       image:"/produk/SAWI PUTIH.jpg",      desc:"Lembut dengan rasa netral. Cocok untuk sup dan kimchi." },
    { name:"Sayur Nangka",     image:"/produk/SAYUR NANGKA.jpg",    desc:"Muda dan berserat. Cocok untuk gudeg dan sayur lodeh." },
    { name:"Seledri",          image:"/produk/SELEDRI.jpg",          desc:"Aroma kuat dan segar. Wajib untuk sup dan masakan berkuah." },
    { name:"Siomak",           image:"/produk/SIOMAK.jpg",           desc:"Daun hijau renyah khas masakan Tionghoa. Cocok untuk tumis." },
    { name:"Terong Ungu",      image:"/produk/TERONG UNGU.jpg",     desc:"Daging lembut saat dimasak. Cocok untuk balado dan panggang." },
    { name:"Timun",            image:"/produk/TIMUN.jpg",            desc:"Segar dan renyah. Favorit untuk lalapan, acar, dan salad." },
    { name:"Toge",             image:"/produk/TOGE.jpg",             desc:"Kecambah segar, renyah. Pelengkap bakso, gado-gado, dan pecel." },
    { name:"Tomat Hijau",      image:"/produk/TOMAT HIJAU.jpg",     desc:"Asam segar, tekstur padat. Cocok untuk sambal dan acar." },
    { name:"Tomat Merah",      image:"/produk/TOMAT MERAH.jpg",     desc:"Matang sempurna dari petani Cianjur. Manis dan rendah pestisida." },
    { name:"Ubi Merah",        image:"/produk/UBI MERAH.jpg",       desc:"Manis alami dengan daging oranye cerah. Cocok untuk kolak dan goreng." },
    { name:"Ubi Putih",        image:"/produk/UBI PUTIH.jpg",       desc:"Bertepung dan mengenyangkan. Serbaguna untuk rebus dan goreng." },
    { name:"Wortel",           image:"/produk/WORTEL.jpg",           desc:"Manis alami, ukuran seragam. Cocok untuk sup, jus, dan salad." },
  ]},
  { id:"cabeBawang", label:"Cabe & Bawang", items:[
    { name:"Bawang Bombay",        image:"/produk/BAWANG BOMBAY.jpg",        desc:"Manis dan aromatik. Dasar masakan Barat dan tumisan Asia." },
    { name:"Bawang Putih",         image:"/produk/BAWANG PUTIH.jpg",         desc:"Aroma kuat, wajib untuk bumbu dasar hampir semua masakan." },
    { name:"Cabai Keriting Hijau", image:"/produk/CABAI KERITING HIJAU.jpg", desc:"Pedas sedang dengan aroma segar. Cocok untuk tumisan dan sambal hijau." },
    { name:"Cabe Merah Besar",     image:"/produk/CABE MERAH BESSAR.jpg",    desc:"Pedas dan berwarna merah cerah. Ideal untuk sambal dan bumbu merah." },
    { name:"Cabe Rawit Hijau",     image:"/produk/CABE RAWIT HIJAU.jpg",     desc:"Pedas tajam dengan aroma segar. Favorit untuk sambal dadak." },
    { name:"Cabe Rawit Merah",     image:"/produk/CABE RAWIT MERAH.jpg",     desc:"Sangat pedas dengan rasa intens. Wajib untuk pecinta sambal." },
    { name:"Cabe Rawit Putih",     image:"/produk/CABE RAWIT PUTIH.png",     desc:"Pedas ringan dengan rasa unik. Cocok untuk sambal putih dan tumisan." },
  ]},
  { id:"buah", label:"Buah", items:[
    { name:"Jeruk Limau",  image:"/produk/JERUK LIMAU.jpg",  desc:"Asam segar, harum kuat. Wajib untuk minuman, sambal, dan kue." },
    { name:"Jeruk Nipis",  image:"/produk/JERUK NIPIS.jpg",  desc:"Segar dan asam. Pelengkap es teh, ayam bakar, dan seafood." },
    { name:"Lemon",        image:"/produk/LEMON.jpg",         desc:"Asam segar khas Barat. Cocok untuk minuman, saus, dan dessert." },
  ]},
  { id:"rempah", label:"Rempah", items:[
    { name:"Daun Bawang",   image:"/produk/DAUN BAWANG.jpg",   desc:"Aroma ringan dan segar. Taburan wajib untuk soto, bakso, dan nasi goreng." },
    { name:"Daun Jeruk",    image:"/produk/DAUN JERUK.jpg",    desc:"Aroma citrus yang khas. Wajib untuk rendang, opor, dan tumisan." },
    { name:"Daun Ketumbar", image:"/produk/DAUN KETUMBAR.jpg", desc:"Aroma segar dan kuat. Cocok untuk salad, kari, dan penyedap." },
    { name:"Daun Salam",    image:"/produk/DAUN SALAM.jpg",    desc:"Harum lembut, khas masakan Indonesia. Wajib untuk gulai dan semur." },
    { name:"Daun Seledri",  image:"/produk/DAUN SELEDRI.jpg",  desc:"Aroma kuat dan segar. Taburan wajib untuk sup dan masakan berkuah." },
    { name:"Jahe",          image:"/produk/JAHE.jpg",           desc:"Serat halus, kadar oleoresin tinggi. Wajib untuk jamu dan minuman rempah." },
    { name:"Kemiri Bulat",  image:"/produk/KEMIRI BULAT.png",  desc:"Kaya lemak alami. Pengental dan pemperkaya rasa bumbu tradisional." },
    { name:"Kemiri Pecah",  image:"/produk/KEMIRI PECAH.png",  desc:"Siap pakai, mudah dihaluskan. Cocok untuk bumbu kacang dan rendang." },
    { name:"Kencur",        image:"/produk/KENCUR.jpg",         desc:"Aroma khas dan kuat. Wajib untuk beras kencur, pecel, dan jamu." },
    { name:"Ketumbar",      image:"/produk/KETUMBAR.jpg",       desc:"Biji bulat beraroma hangat. Penyedap utama untuk sate dan gulai." },
    { name:"Kunyit",        image:"/produk/KUNYIT.jpg",         desc:"Warna kuning cerah, rasa khas. Wajib untuk nasi kuning dan kari." },
    { name:"Lengkuas",      image:"/produk/LENGKUAS.jpg",       desc:"Aroma tajam dan pedas khas. Wajib untuk ayam bakar dan rendang." },
    { name:"Merica",        image:"/produk/MERICA.jpg",         desc:"Pedas hangat yang khas. Penyedap universal untuk semua jenis masakan." },
    { name:"Sereh",         image:"/produk/SEREH.jpg",          desc:"Aroma citrus segar dan kuat. Wajib untuk soto, tom yam, dan gulai." },
    { name:"Singkong",      image:"/produk/SINGKONG.jpg",       desc:"Bertepung dan mengenyangkan. Cocok untuk direbus, digoreng, atau diolah menjadi tepung." },
  ]},
];

export const CLIENTS = [
  { mark:"A", name:"Artisan Kuliner Group",     cat:"F&B Group",        loc:"Jakarta",   img:"/partners/ARTISAN KULINER GROUP.png" },
  { mark:"B", name:"Boga Group",                cat:"F&B Group",             loc:"Nasional",  img:"/partners/bogagroup.png" },
  { mark:"D", name:"Dapur Solo",                cat:"Restoran Chain",              loc:"Tangerang", img:"/partners/DAPUR SOLO.png" },
  { mark:"D", name:"Din Tai Fung",              cat:"Restoran Chain", loc:"Jakarta",  img:"/partners/DIN TAI FUNG.png" },
  { mark:"E", name:"Excelso",                   cat:"Rantai Kafe",           loc:"Nasional",  img:"/partners/EXCELSO.png" },
  { mark:"H", name:"Holywings",                 cat:"Restoran Chain",        loc:"Nasional",  img:"/partners/HOLYWINGS.jpg" },
  { mark:"H", name:"Hong Tang",                 cat:"Dessert Chain",         loc:"Jabodetabek", img:"/partners/HONG TANG.png" },
  { mark:"G", name:"GF Culinary Group",          cat:"F&B Group",             loc:"Jakarta",   img:"/partners/gfculinary.jpg" },
  { mark:"M", name:"Mangkokku",                 cat:"Restoran Chain",             loc:"Nasional",  img:"/partners/MANGKOKKU.png" },
  { mark:"B", name:"Bittersweet by Najla",       cat:"Restoran",              loc:"Jakarta",   img:"/partners/bittersweet.jpg" },
  { mark:"S", name:"Se'Indonesia",               cat:"Restoran Chain",  loc:"Nasional",  img:"/partners/seindonesia.webp" },
  { mark:"S", name:"Sate Khas Senayan",         cat:"Restoran Chain",  loc:"Jakarta",   img:"/partners/SATE KHAS SENAYAN.jpg" },
  { mark:"Y", name:"Yellow Fit Kitchen",        cat:"Katering",    loc:"Nasional",  img:"/partners/YELLOW FIT KITCHEN.png" },
];

export const NAV_LINKS = [
  { id:"home",   label:"Beranda",   href:"/" },
  { id:"katalog",label:"Katalog",   href:"/katalog" },
  { id:"cara",   label:"Cara Kerja",href:"/cara-kerja" },
  { id:"blog",   label:"Blog",      href:"/blog" },
  { id:"tentang",label:"Tentang",   href:"/tentang" },
];

export const BLOG_POSTS = [
  {
    slug:      "harga-grosir-sayuran-jakarta-2025",
    title:     "Harga Grosir Sayuran Jakarta 2025: Panduan Pembelian B2B",
    excerpt:   "Tinjauan harga grosir sayuran Jakarta 2025 untuk restoran, hotel & catering — kisaran harga per kategori, faktor fluktuasi, dan strategi mengunci harga.",
    category:  "Insight Pasar",
    date:      "2026-05-19",
    readTime:  "7 menit",
  },
  {
    slug:      "cara-memilih-supplier-sayuran-untuk-restoran",
    title:     "Cara Memilih Supplier Sayuran untuk Restoran: 7 Kriteria Penting",
    excerpt:   "Framework praktis untuk pemilik restoran dalam mengevaluasi calon supplier sayuran — 7 kriteria, daftar pertanyaan negosiasi, dan red flags.",
    category:  "Panduan",
    date:      "2026-05-19",
    readTime:  "6 menit",
  },
  {
    slug:      "distributor-sayuran-segar-untuk-restoran",
    title:     "Distributor Sayuran Segar untuk Restoran: Panduan Lengkap 2026",
    excerpt:   "Memahami cara kerja distributor sayuran segar untuk restoran — struktur harga, MOQ, jadwal pengiriman, dan kriteria memilih mitra yang tepat.",
    category:  "Panduan",
    date:      "2026-05-19",
    readTime:  "7 menit",
  },
  {
    slug:      "cara-cek-kualitas-sayuran",
    title:     "Cara Cek Kualitas Sayuran Sebelum Diterima di Dapur",
    excerpt:   "Panduan praktis untuk staf dapur dan pemilik restoran dalam memastikan bahan sayuran yang diterima benar-benar segar dan layak masak.",
    category:  "Panduan",
    date:      "2026-05-10",
    readTime:  "5 menit",
  },
];
